### ISSUE TITLE
`exclude` only works on module names, not import paths

### ISSUE THREAD

**Issue by elado** [Septh/rollup-plugin-node-externals#10]
## Issue

`exclude` option only filters out modules by their name, not by an import path.
So while it's possible to exclude something like `/^lodash/` (covers `lodash`, `lodash-es` etc) it's not possible to exclude specifically sub paths or files by extensions.

## Use case:

- I have a package with some imports, e.g. `import Foo from 'foo'; import 'foo/index.css'`
- I use `postcss({extract: true})`, expecting all imported css to end up in `dist/index.css`
- With this plugin, both `foo` and `foo/index.css` end up as externals
- Using `exclude: /\.css$/` doesn't work

## Solution

Ideal solution is to be able to have `exclude` also match against import path in `resolveId`.

```js
externals({ deps: true, exclude: [/\.css$/] }),
```

**Comment by Septh** [comment]
Actually, `exclude` **does** work as publicized, even on import paths. :)

Your issue is not with this plugin but with the way you use PostCSS.

The thing is, `postcss({extract: true})` generates an assets file which is external by nature (it is linked to your HTML via its HEAD tag). See [rollup-plugin-postcss's documentation](https://github.com/egoist/rollup-plugin-postcss#readme) for details.

I'm closing this issue but feel free to comment further if need be.

**Comment by Septh** [comment]
Sorry for the delayed answer, I'm quite busy right now. I'll be looking into this shortly.

**Comment by TomerAberbach** [comment]
@Septh, I can probably find the time to fix this if you're too busy. Let me know!

**Comment by Septh** [comment]
_Wow... 9 months already?!? This must be a world record! :grimacing:_

I'm **so** sorry for the delay. I really am.

I just released v3.0.0 which fixes this issue. Hope it works for you.

**Comment by elado** [comment]
Thank you! It works! 👑
