### ISSUE TITLE
change of type crashes my electron app

### ISSUE THREAD

**Issue by hmt** [Septh/rollup-plugin-node-externals#11]
Ever since v3 my electron app won't run because rollup complains about a mixup between commonjs and esm. I had to revert to v2 and that works just fine for me. 
Anyway, thank you very much for your plugin!

**Comment by lmestel** [comment]
I just run into the same issue. 

`find-up` [version 6 is ESM only](https://github.com/sindresorhus/find-up/releases/tag/v6.0.0), so `const findUp = require('find-up');` (from your dist/cjs/index.js) throws an error:

> Error [ERR_REQUIRE_ESM]: Must use import to load ES Modul

**Comment by Septh** [comment]
Right. TBH, I'm beginning to get really, really, really tired of those commonjs/esm issues 😢 

@lmestel > could you please try with 3.0.0 and tell me if it works? `find-up` was mistakenly bundled in 3.0.0, which is why I released 3.0.1. But in the end, it could just be the right way to go.

@hmt > is your issue related to @lmestel's or completely different?

**Comment by hmt** [comment]
no, it's different. Doesn't say exactly what's wrong, doesn't even mention this plugin by name.

**Comment by lmestel** [comment]
> I'm beginning to get really, really, really tired of those commonjs/esm issues

I feel you!

> could you please try with 3.0.0

Oh, I didn't mention, that the error ocoured with version 3.1.0. 
With 3.0.0 the build workes! 👍 
But I had to change `const externals = require('rollup-plugin-node-externals');` into `const { default: externals } = require('rollup-plugin-node-externals');` (otherwise I get `TypeError: externals is not a function` 🤷)

**Comment by Septh** [comment]
This is hopefully fixed in 3.1.1. Please let me know.

**Comment by hmt** [comment]
Thank you! It works again. I don't even know why I need your plugin but it somehow solves a bunch of issues I have when trying to build my app without :S

**Comment by lmestel** [comment]
👍 Thank you very much!
