### ISSUE TITLE
... is not assignable to type 'PluginOption'

### ISSUE THREAD

**Issue by unional** [Septh/rollup-plugin-node-externals#17]
Getting this warning when using with `vite` with `vite.config.ts`:

![image](https://user-images.githubusercontent.com/3254987/206557045-a1807aa0-5843-4eaf-bbfc-aa4f5233f7f2.png)

```
Type '{ enforce: "pre"; api?: any; cacheKey?: string | undefined; name: string; augmentChunkHash?: ObjectHook<(this: PluginContext, chunk: RenderedChunk) => string | void, {}> | undefined; ... 24 more ...; watchChange?: ObjectHook<...> | undefined; }' is not assignable to type 'PluginOption'.
```

```sh
vite: 3.2.5
rollup-plugin-node-externals: 5.0.2
typescript: 4.9.3
```

**Comment by Septh** [comment]
Hey, thank you for reporting this!

As far as I can tell, this happens because of a Vite and Rollup typings mismatch that may show up when you update your project's dependencies.

The best way to fix this is to delete your `node_modules` folder and `package-lock.json` file, then run `npm install` again to start afresh.

If you can't go this way, you may safely silent this warning by either adding a `// @ts-ignore` directive or asserting the type to `any`.

```ts
// vite.config.ts

export default defineConfig({
  plugins: [
    { ...externals(), enforce: 'pre' } as any
  ]
})

```

**Comment by unional** [comment]
Thanks. Yes. But deleting `node_modules` doesn't help.
What happens is that `rollup-plugin-node-externals` 5.02 is using `rollup` 3.5.0,
while `vite` 3.2.4 is still using `rollup` 2.79.1.

Will try to upgrade to `vite` 4, that probably will solve the problem. 🌷

**Comment by Septh** [comment]
That's strange, because my plugin has a peer dependency on `Rollup ^2.60.0 || ^3.0.0`, so it should not force the installation of V3 if V2 is available.

FWIW, I did some testing on an empty directory and it appears that `npm install vite@3 rollup-plugin-node-externals` results in installing both Rollup v2 (in Vite's own `node_modules`) and V3 (in the root `node_modules`), while `npm install vite@3` first followed by `npm install rollup-plugin-node-externals` results in having only V2 in the root `node_modules` directory. So I guess this is npm's behavior to prefer newest packages versions whenever possible.

Anyway, upgrading to Vite 4 should indeed fix your problem.

**Comment by unional** [comment]
FYI, after I updated to `vite` 4, the issue is still there.

```sh
Type '{ enforce: "pre"; api?: any; cacheKey?: string; name: string; augmentChunkHash?: ObjectHook<(this: PluginContext, chunk: PreRenderedChunk) => string | void, {}>; ... 25 more ...; watchChange?: ObjectHook<...>; }' is not assignable to type 'PluginOption'.
  Type '{ enforce: "pre"; api?: any; cacheKey?: string; name: string; augmentChunkHash?: ObjectHook<(this: PluginContext, chunk: PreRenderedChunk) => string | void, {}>; ... 25 more ...; watchChange?: ObjectHook<...>; }' is not assignable to type 'false'.
  ```

I have deleted node_modules and do `pnpm i` again. 😞
