### ISSUE TITLE
Question about defaults

### ISSUE THREAD

**Issue by onlywei** [Septh/rollup-plugin-node-externals#29]
Suppose we are making a package that we want to publish to npm.

My understanding of `dependencies`, `devDependencies`, and `peerDependencies` is as follows:

1. `dependencies` are packages that we do not want the people who download our package to ever really have to think about, so we bundle them into our dist file. We do **not** put them into our bundler's "externals" config.
2. `devDependencies` are things like unit test runners, eslint, and rollup itself. We should never be importing them into our source code, and therefore it's irrelevant whether we include them into "externals" or not.
3. `peerDependencies` are packages which we want the people who download our package to ALSO install. Therefore we put them into the "externals" config to prevent duplication between our bundle and the downloaders' installations.

This understanding does not seem to match with the defaults of this plugin. My understanding is that the defaults should be:

```
deps: false
devDeps: false
peerDeps: true
```

Can someone explain what is different between my understanding and this plugin's philosophy?

**Comment by Septh** [comment]
You've got it partly right -- and hence, partly wrong.

1. `dependencies` are packages that are needed to run/use your package _at run time_. They are _not_ bundled with your package (meaning, they are not physically part of it); instead, `npm` will automatically download and install them alongside your package when a user runs `npm install <your-package>`.<br>They should always be `external` because if Rollup bundled them there would be code duplication between the code of your package and the user's installation.
2. `devDependencies` are support packages that are needed to _build_ your package. As you said, those include things like test runners, linters, and Rollup itself. But if you ask Rollup to bundle some package inside you code, then that package is a _development dependency_ also (it is needed to build your package but not to run/use it since it is bundled).<br>`devDependencies` should _not_ be `external` as otherwise Rollup would not bundle them and your package would simply not work at run time.<br>And of course, `devDependencies` are only bundled if your code actually requires/imports them.
3. `peerDependencies` are very similar to `dependencies`, but the other way around: they do not express packages that are needed by your package but packages that can require/import yours.

There are many blog posts and tutorials on the Web that may give you a better understanding, like [this one](https://medium.com/@DevChris01/npm-dependencies-vs-devdependencies-vs-peerdependencies-82760bd630d) or [that one](https://www.geeksforgeeks.org/difference-between-dependencies-devdependencies-and-peerdependencies/).

Therefore, this plugin's defaults are exactly right: only `devDependencies` are bundled (not external), all other kinds of dependencies are external (not bundled).

```js
deps: true       // external
devDeps: false   // *not* external
peerDeps: true   // external
optDeps: true    // external
```

**Comment by onlywei** [comment]
I think we are agreed with regards to `devDependencies` and `peerDependencies`. The following defaults are correct:

```
devDeps: false
peerDeps: true
optDeps: true
```

I want to push a little more on `dependencies`.

You say that:

> npm will automatically download and install them alongside your package when a user runs npm install <your-package>

I agree with this statement. However, I worry that this is dependent on npm's flattened `node_modules` structure. Because both the dependencies _and_ transitive dependencies of a project are located as siblings within the `node_modules` directory, a project is able to require/import from a transitive dependency without error.

Flattened `node_modules` looks like the following, where `dependency-a` depends on `dependency-b`:

```
node_modules/
-  dependency-a/
-  dependency-b/
```

If instead you are using `pnpm`, the `node_modules` directory is NOT flattened (similar to early npm) and instead looks like:

```
node_modules/
-  dependency-a/
  -  node_modules/
    -  dependency-b/
```

Are you sure the runtime will still be able to pick up `dependency-b` if it's not bundled in that kind of `node_modules` structure?

**Comment by Septh** [comment]
This discussion is going far beyond the scope of Rollup and my plugin but in a nutshell: both Node's [CommonJS](https://nodejs.org/api/modules.html#modules_all_together) and [ESM](https://nodejs.org/api/esm.html#resolution-and-loading-algorithm) resolution algorithms work regardless of the `node_modules` folder being flattened or not. Choosing whether a dependency should be bundled by Rollup or dynamically loaded at runtime is therefore irrelevant to the `node_modules` structure; instead other considerations come into play such as whether you are building an app or a library, targeting the browser or the NodeJS runtime, bootstrap performance, ease of dependencies update etc.

**Comment by onlywei** [comment]
Thanks for the response! I understand now!
